<?php

/** Generated by Latte 3.0.24 */

use Latte\Runtime as LR;

/** source: create.latte */
final class Template_2d9ae97103 extends Latte\Runtime\Template
{
	public const Source = 'create.latte';

	public const Blocks = [
		['content' => 'blockContent'],
	];


	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		echo "\n";
		$this->renderBlock('content', get_defined_vars()) /* line 3 */;
	}


	public function prepare(): array
	{
		extract($this->params);

		$this->parentName = 'layout.latte';
		return get_defined_vars();
	}


	/** {block content} on line 3 */
	public function blockContent(array $ʟ_args): void
	{
		extract($this->params);
		extract($ʟ_args);
		unset($ʟ_args);

		echo '    <h2>';
		echo LR\Filters::escapeHtmlText($title) /* line 4 */;
		echo '</h2>
    <form method="POST" action="/create">
        <div class="form-group">
            <label for="title">Título:</label>
            <input type="text" name="title" id="title" required>
        </div>
        <div class="form-group">
            <label for="content">Contenido:</label>
            <textarea name="content" id="content" required></textarea>
        </div>
        <button type="submit">Guardar Publicación</button>
    </form>
';
	}
}
