<?php

/** Generated by Latte 3.0.24 */

use Latte\Runtime as LR;

/** source: home.latte */
final class Template_222334a776 extends Latte\Runtime\Template
{
	public const Source = 'home.latte';

	public const Blocks = [
		['content' => 'blockContent'],
	];


	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		echo "\n";
		$this->renderBlock('content', get_defined_vars()) /* line 3 */;
	}


	public function prepare(): array
	{
		extract($this->params);

		if (!$this->getReferringTemplate() || $this->getReferenceType() === 'extends') {
			foreach (array_intersect_key(['post' => '6'], $this->params) as $ʟ_v => $ʟ_l) {
				trigger_error("Variable \$$ʟ_v overwritten in foreach on line $ʟ_l");
			}
		}
		$this->parentName = 'layout.latte';
		return get_defined_vars();
	}


	/** {block content} on line 3 */
	public function blockContent(array $ʟ_args): void
	{
		extract($this->params);
		extract($ʟ_args);
		unset($ʟ_args);

		echo '    <h2>';
		echo LR\Filters::escapeHtmlText($title) /* line 4 */;
		echo '</h2>
    <ul>
';
		foreach ($posts as $post) /* line 6 */ {
			echo '        <li><a href="/post/';
			echo LR\Filters::escapeHtmlAttr($post['slug']) /* line 7 */;
			echo '">';
			echo LR\Filters::escapeHtmlText($post['title']) /* line 7 */;
			echo '</a></li>
';

		}

		echo '    </ul>
';
	}
}
