<?php

/** Generated by Latte 3.0.24 */

use Latte\Runtime as LR;

/** source: layout.latte */
final class Template_c88f365b73 extends Latte\Runtime\Template
{
	public const Source = 'layout.latte';

	public const Blocks = [
		['content' => 'blockContent'],
	];


	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		echo '<!DOCTYPE html>
<html>
<head>
<title>';
		echo LR\Filters::escapeHtmlText($title) /* line 4 */;
		echo '</title>
</head>
<body>
<header>
    <h1>Mi Blog</h1>
    <nav>
        <a href="/">Inicio</a> | 
        <a href="/create">Crear una Publicación</a>
    </nav>
</header>
<main>
';
		$this->renderBlock('content', get_defined_vars()) /* line 15 */;
		echo '</main>
<footer>
    <p>&copy; ';
		echo LR\Filters::escapeHtmlText(date('Y')) /* line 18 */;
		echo ' Blog Flight</p>
</footer>
</body>
</html>';
	}


	/** {block content} on line 15 */
	public function blockContent(array $ʟ_args): void
	{
	}
}
