<?php

/** Generated by Latte 3.0.24 */

use Latte\Runtime as LR;

/** source: post.latte */
final class Template_64074e95f7 extends Latte\Runtime\Template
{
	public const Source = 'post.latte';

	public const Blocks = [
		['content' => 'blockContent'],
	];


	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		echo "\n";
		$this->renderBlock('content', get_defined_vars()) /* line 3 */;
	}


	public function prepare(): array
	{
		extract($this->params);

		$this->parentName = 'layout.latte';
		return get_defined_vars();
	}


	/** {block content} on line 3 */
	public function blockContent(array $ʟ_args): void
	{
		extract($this->params);
		extract($ʟ_args);
		unset($ʟ_args);

		echo '    <h2>';
		echo LR\Filters::escapeHtmlText($post['title']) /* line 4 */;
		echo '</h2>
    <div class="post-content">
        <p>';
		echo LR\Filters::escapeHtmlText($post['content']) /* line 6 */;
		echo '</p>
    </div>
';
	}
}
